const API_BASE = 'http://localhost:8000/api/v1'
const API_KEY_STORAGE_KEY = 'transitpulse_api_key'

// Local-dev auth bridge: until a real Clerk account is configured, requests
// authenticate via an API key (X-API-Key) generated by
// `python -m app.scripts.seed_dev_org`. Swapping this for Clerk session
// auth later means changing only getApiKey()/setApiKey() and how the
// Authorization header is built here — request() and every caller stay
// the same.
export function getApiKey() {
  return localStorage.getItem(API_KEY_STORAGE_KEY) || ''
}

export function setApiKey(key) {
  localStorage.setItem(API_KEY_STORAGE_KEY, key.trim())
}

export function clearApiKey() {
  localStorage.removeItem(API_KEY_STORAGE_KEY)
}

async function request(path) {
  const apiKey = getApiKey()
  const res = await fetch(`${API_BASE}${path}`, {
    headers: apiKey ? { 'X-API-Key': apiKey } : {},
  })
  if (!res.ok) {
    if (res.status === 401) clearApiKey()
    throw new Error(`Request to ${path} failed with ${res.status}`)
  }
  return res.json()
}

export function fetchMe() {
  return request('/orgs/me')
}

export function fetchRoutes() {
  return request('/routes')
}

export function fetchTrips(routeExternalId) {
  return request(`/routes/${routeExternalId}/trips`)
}

export function fetchCrowding(tripId) {
  return request(`/trips/${tripId}/crowding`)
}
